List<String> deportment = [
  'Department of Biotechnology',
  'Department of Biochemistry',
  'Department of Botany',
  'Department of Computer Science & IT',
  'Department of Chemistry',
  'Department of Economics',
  'Department of Education',
  'Department of English',
  'Department of Geology',
  'Department of Islamic Studies',
  'Department of Journalism',
  'Department of Management',
  'Department of Mathematics',
  'Department of Pashto',
  'Department of Political Science',
  'Department of Pharmacy',
  'Department of Physics',
  'Department of Psychology',
  'Department of Sociology',
  'Department of Software Engineering',
  'Department of Statistics',
  'Department of Tourism',
  'Department of Zoology',
];
